name: Renew the CA-verified Certificate

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 on the 1st and 15th day of every month. (see https://crontab.guru)
    - cron: "0 0 1,15 * *"

jobs:
  build:
    name: Trigger Juju renew certificate action on certbot-k8s
    runs-on: ubuntu-latest
    steps:
      - name: Renewing Certificate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # The model name is "waltz-model-v3"
            juju switch waltz-model-v3
                    
            # Running juju status will show us the current revisions of the charms.
            juju status --relations

            # Run the renew action on the certbot-k8s charm.
            echo "Running renew-certificate action..."
            action_result=$(juju run certbot-k8s/0 renew-certificate --wait=10m)
            echo "The renew-certificate action finished with the result: ${action_result}"

            if [[ $? -ne 0 ]]; then
              echo "Certificate renewal failed:\n$action_result" 
              exit 1
            fi

            # Show the juju status to see if any errors occurred.
            juju status --relations

      - name: Send email on failure
        if: failure() && github.event_name == 'schedule'
        uses: vineetchoudhary/mailgun-action@master
        with:
          api-key: ${{ secrets.MAILGUN_API_KEY }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          to: ${{ secrets.EMAIL_TO }}
          subject: "${{ github.job }} job of ${{ github.repository }} has failed"
          body: "${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Send Mail Action Response
        run: echo "${{ steps.sendmail.outputs.response }}"
